name: setup-aws-cli
description: setup aws-cli v2
runs:
  using: composite
  steps:
    # https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
    - shell: bash
      run: |
        set -eux
        if aws --version; then
          exit
        fi
        cd "$(mktemp -d)"
        curl -sf "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o awscliv2.zip
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        aws --version
