name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # delete preexisting one
      - run: sudo rm -fr /usr/local/aws-cli
      - uses: ./
