name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  when-aws-cli-does-not-exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # delete preexisting one
      - run: sudo rm -fr /usr/local/aws-cli
      - uses: ./

  when-aws-cli-already-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
